name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd manager/; docker build .  -f Dockerfile.manager -t rikencau/abart-manager:latest -t rikencau/abart-manager:$(date +%s)


